name: "Deploy to Vercel "

on: push
  # workflow_run:
  #   workflows: ["test","lint"]
  #   branches: [main]
  #   types: 
  #     - completed
  # push:
  #   branches:
  #     - main
env:
  NODE_VERSION: 16
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
jobs:
  vercel: 
    runs-on: ubuntu-latest
    name: "Deploy porfolio"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: npm ci
      - name: "Deploy to Vercel"
        run: npx vercel --token ${VERCEL_TOKEN} --prod
          