# This workflow will do test lint

name: Porfolio CI

on:
  push:
    branches: [ main, init ]
  pull_request:
    branches: [ main, init ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@init
    - name: Lint Markdown
      uses: actionshub/markdownlint@init
    - run: npm ci
    - run: npm run lint
